name: crop-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit
      - numpy
      - pillow
      - opencv-python
      - huggingface-hub
      - tensorflow==2.12.0
      - keras==2.12.0
